from pydantic import BaseModel, Field
from typing import Annotated, Literal
from operator import add

class AgentSchema(BaseModel):
    messages: Annotated[list,add]=Field(..., description = "List of messages to be processed by the agent.")
    user_question: str = Field(..., description = "Original user question that needs to be answered by the agent.")
    curated_ques: str = Field(..., description = "Curated user question")
    prompt_query_context: str = Field(..., description = "A detailed prompt with SQL DB context that will help agent to generate SQL Query")
    is_safe: Literal["Yes","No"] = Field(..., description  = "Indicates whether the gennerated SQL query is safe to execute or not")
    generated_sql_query : str = Field(..., description = "SQL query generated by the agent based on the curated question and prompt context.") 
    sql_query_execution_result : str = Field(..., description = "Result of the executing sql query on the database")
    final_answer : str = Field(..., description = "Final answer generated by the agent based on the sql query execution result and curated question.")

class JudgeSchema(BaseModel):
    answer: Literal["Yes", "No"] = Field(..., description = "Indicates whether the generated SQL query is safe to execute or not")
    comments: str = Field(..., description = "Comments or reasoning behind the judgment of the SQL query's safety.")

class ETLAgentSchema(BaseModel):
    messages:Annotated[list,add]=Field(...,description="List of messages to be processed by ETL Agent")

class RouterSchema(BaseModel):
    answer: Literal['sql','etl'] = Field(...,description="Indicates whether the user's question is related to SQL or ETL operations")
    comments: str = Field(...,description="Additional comments or feedback regarding the classification of the user's question")

class DataAgentSchema(BaseModel):
    messages : Annotated[list,add] = Field(..., description="List of messages to be processed by the Data agent")
    route_response : str = Field(..., description="The response from the router indicating whether to route to SQL or ETL operations")

